API_KEY = "cK6gXtu2fEVFZmDbhuZUUrYgMSFoEi1vFXwsvaE7h30C35WZt63QJQQJ99BIACmepeSXJ3w3AAAAACOGZxX7"
FULL_API_URL = "https://cvprofilefoundry-test.cognitiveservices.azure.com/openai/deployments/gpt-4o-2024-08-06-CVProfiler-v1-3/chat/completions?api-version=2025-01-01-preview"
